---
title: "Rafid Shaon - Monte Carlo"
date: "04/09/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulation Code

```{r}
Ncomputers=20 #Number of computer in the Network
Nclean=5;
N=10000 #Total Simulation
prob=0.1 # Probability of infected

save_Days=rep(NA,N)
save_count_infected=matrix(rep(NA,N*Ncomputers),N,Ncomputers)

for (j in 1:N)
{
  infected=rep(0,Ncomputers)
  count_infected=rep(0,Ncomputers)
  Each_infected<-NULL
  # One computer becomes infected with a virus
  a=sample(1:Ncomputers, 1,replace=TRUE) # Random number from 1 to 20
  infected[a]=1  # One computer becomes infected with a virus

  
  # Count the infected computer
  count_infected[a]=count_infected[a]+1;
  
  days=1;
  h=1;
  while(sum(infected)>0)
  {  
    # Infected all network with Prob=0.1
    k=length(a)
    while(k<=length(a))
    {
      for(i in 1:Ncomputers)
      { 
        if(sum(i==a)==0)
        {
           if(runif(1)<prob)
           {
              infected[i]=1;
              count_infected[i]=count_infected[i]+1;
              a=c(a,i)
            }
        }
      }
      k=k+1;
    }
    
     Number_infected=
  # Removes the virus from 5 computer
    if(sum(infected)<=5){
      infected=rep(0,Ncomputers)
    } else {
      remove=sample(a, Nclean, replace = FALSE);
      infected[remove]=0;
      a=a[!a %in% remove]
    }
days=days+1;
}
save_Days[j]=days
save_count_infected[j,]=count_infected
}
```

-   The expected time it takes to remove the virus from the whole network

```{r}
mean(save_Days)
```

-   The probability that each computer gets infected at least one

```{r}
each_infected=rep(1,N)
for(k in 1:N){ 
if(sum(save_count_infected[k,]==0)>0)   
 each_infected[k]=0;
}
Probability=sum(each_infected)/N
Probability
```

-   The expected number of computers that get infected

```{r}
Total_computer_infected=rep(0,N)
for(k in 1:N){ 
  Total_computer_infected[k]=sum(save_count_infected[k,])   
}
mean(Total_computer_infected)
```